services:
  nfc_quest:
    image: ghcr.io/vvzvlad/nfc_quest:latest
    container_name: nfc_quest
    volumes:
      - nfc_quest:/app/data
    environment:
      TZ: Europe/Moscow
      ADMIN_PASSWORD: хххх
      BASE_URL: https://nfc......cc
      QUEST_NAME: хххх
    restart: always
    networks:
      - docker_main_net
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    labels:
      traefik.enable: true
      traefik.http.routers.nfc_quest.rule: Host(`хххх`)
      traefik.http.services.nfc_quest.loadBalancer.server.port: 5000
      traefik.http.routers.nfc_quest.entrypoints: websecure
      traefik.http.routers.nfc_quest.tls.certresolver: letsEncrypt
      traefik.http.routers.nfc_quest.tls: true
      traefik.http.routers.nfc_quest.priority: 100

      com.centurylinklabs.watchtower.enable: true

volumes:
  nfc_quest:

networks:
  docker_main_net:
    external: true